# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yammerstats}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Moran"]
  s.date = %q{2009-12-07}
  s.default_executable = %q{yammerstats}
  s.description = %q{Fetches Yammer information and outputs it to the format of your choice, using Erb templates.}
  s.email = %q{workingpeter@gmail.com}
  s.executables = ["yammerstats"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/yammerstats",
     "examples/data/users.json",
     "examples/html/FCF_Column3D.swf",
     "examples/html/top_updaters.html",
     "examples/templates/top_updaters.erb",
     "lib/ext/yammer/client.rb",
     "lib/yammer/stats.rb",
     "lib/yammerstats.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/yammer/stats_spec.rb"
  ]
  s.homepage = %q{http://github.com/pmoran/yammerstats}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Fetch some (possibly) useful info from your Yammer domain}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/yammer/stats_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

